development:
  adapter:  postgresql
  host:     127.0.0.1
  encoding: unicode
  database: myapp_development
  pool:     5
  username: adityakapoor
  password:
  template: template0
test:
  adapter:  postgresql
  host:     127.0.0.1
  encoding: unicode
  database: myapp_test
  pool:     5
  username: adityakapoor
  password:
  template: template0
